### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by SystemFw** [typelevel/CT_from_Programmers.scala#5]
Given the degree of flexibility in translating Haskell to Scala, it would be good to have a short style guide. In particular, it's crucial imho that the we decide on how to translate functions:
- scala functions
- scala methods with multiple parameter lists
- scala methods with a single parameter list

Even if we decide that it's best to translate functions in different ways depending on the scenario, this should be documented

**Comment by kailuowang** [comment]
Totally, we can just put it in the readme. You wanna draft one? Or I can do later today or tomorrow.

**Comment by SystemFw** [comment]
So, I'm not quite sure myself what the best approach is. 
Using functions is closer to the idea of morphism (at least visually, people won't have to translate in their head), but it will likely cause problems going forward given that methods are much more powerful
