### ISSUE TITLE
Keep track of ongoing work

### ISSUE THREAD

**Issue by SystemFw** [typelevel/CT_from_Programmers.scala#8]
I'm thinking we should have a way of tracking how many things have been translated/what's left to do. I don't particularly care which method we use (issue with checklist perhaps?)

**Comment by kailuowang** [comment]
How about we create a list of issues one for each page, so people can assign themselves? We can mention it in the readme as well.

**Comment by SystemFw** [comment]
I'll have a look at the Github Api to do this

**Comment by kailuowang** [comment]
I can manually create them if it's easier.

**Comment by SystemFw** [comment]
No it's ok, I just didn't have a single second to look into it. Doing it now :)

**Comment by SystemFw** [comment]
I have all the requests ready. I just need to figure out how to authenticate. 😞

**Comment by SystemFw** [comment]
Cool, I have it. They should be created shortly

**Comment by SystemFw** [comment]
Done!  Some of them might need closing already since the translation has already been done

https://xkcd.com/1319/

**Comment by kailuowang** [comment]
yup, I already closed 1.1-1.4. Thanks so much @SystemFw

**Comment by SystemFw** [comment]
No worries :) I'll start translating myself as soon as I find some time
